version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=201213138060tbt,
      - MYSQL_PASSWORD=201213138060tbt,
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=towavephone

  app:
    image: nextcloud
    ports:
      - 8090:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
