version: '2'

services:
  verdaccio:
    image: verdaccio/verdaccio:3.0.0
    container_name: verdaccio
    ports:
      - "4873:4873"
    volumes:
        - "./storage:/verdaccio/storage"
        - "./conf:/verdaccio/conf"
